# define base image
FROM chuanwen/cowsay  

# Define an Entrypoint
ENTRYPOINT [ "/usr/games/cowthink" ]

#define parameters for the entrypoint
CMD ["#VQV Trybe"]

# At terminal
# build an image
# docker build -t cowsay:v1

# create and run a container 
# docker container run cowsay:v1

# run a different char
# docker container run cowsay:v1 -l (will shows other char options to print)

# docker container run cowsay:v1 -f (chosen char) "string message"
# ex: docker container run cowsay:v1 -f ghostbusters "VQV TRYBE"
